// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU83yd3CPol08XgUBHKjSXORjbEkUcIKU',
    appId: '1:388931985055:web:647f9b6ec89658dfe14caa',
    messagingSenderId: '388931985055',
    projectId: 'cuet-33bdf',
    authDomain: 'cuet-33bdf.firebaseapp.com',
    storageBucket: 'cuet-33bdf.firebasestorage.app',
    measurementId: 'G-JRV8S17CZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRdn_S57mqSVfufek56Jo718QMXZClcpI',
    appId: '1:388931985055:android:6a1916c6dcacf6fce14caa',
    messagingSenderId: '388931985055',
    projectId: 'cuet-33bdf',
    storageBucket: 'cuet-33bdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMc2yH-DhhhQO_bkKznpQnkykLcQ4dwGs',
    appId: '1:388931985055:ios:89db405aef985f3fe14caa',
    messagingSenderId: '388931985055',
    projectId: 'cuet-33bdf',
    storageBucket: 'cuet-33bdf.firebasestorage.app',
    iosBundleId: 'com.example.cuetCseCourseMaterialsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMc2yH-DhhhQO_bkKznpQnkykLcQ4dwGs',
    appId: '1:388931985055:ios:89db405aef985f3fe14caa',
    messagingSenderId: '388931985055',
    projectId: 'cuet-33bdf',
    storageBucket: 'cuet-33bdf.firebasestorage.app',
    iosBundleId: 'com.example.cuetCseCourseMaterialsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU83yd3CPol08XgUBHKjSXORjbEkUcIKU',
    appId: '1:388931985055:web:74cd562b7a94de2ae14caa',
    messagingSenderId: '388931985055',
    projectId: 'cuet-33bdf',
    authDomain: 'cuet-33bdf.firebaseapp.com',
    storageBucket: 'cuet-33bdf.firebasestorage.app',
    measurementId: 'G-M7MYC0M0SN',
  );
}
